# Generated by Django 4.2.5 on 2023-09-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_genrefilmwork_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='genrefilmwork',
            name='filmwork_genre_idx',
        ),
        migrations.RemoveIndex(
            model_name='personfilmwork',
            name='person_filmwork_idx',
        ),
        migrations.AddConstraint(
            model_name='genrefilmwork',
            constraint=models.UniqueConstraint(fields=('film_work', 'genre'), name='filmwork_genre_unique'),
        ),
        migrations.AddConstraint(
            model_name='personfilmwork',
            constraint=models.UniqueConstraint(fields=('film_work', 'person', 'role'), name='film_work_person_role_unique'),
        ),
    ]
